import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import CustomNavbar from "@/components/CustomNavbar";
import Footer from "@/components/Footer";
import { Suspense } from 'react';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<p>Loading feed...</p>}>
          <ToastContainer />
        </Suspense>
        <CustomNavbar />
        <div className="mt-2">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
